name: Call DLT
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # เพิ่มบรรทัดนี้เพื่อให้กดรันเองได้

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: curl https://kanchanaburi.dlt.go.th/TLnotication/check_and_send_mail
