name: Call DLT
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: curl -k https://kanchanaburi.dlt.go.th/TLnotication/check_and_send_mail
